
/*  DEFERRABLE CONSTRAINTS */

CREATE TABLE FUNCIONARIO(
    ID_FUNCIONARIO INT CONSTRAINT PK_FUNCIONARIO PRIMARY KEY,
    NOME VARCHAR2(100)
);

DROP TABLE TELEFONE;

CREATE TABLE TELEFONE(
    ID_TELEFONE INT PRIMARY KEY,
    NUMERO VARCHAR2(11),
    ID_FUNCIONARIO INT
);

ALTER TABLE TELEFONE ADD CONSTRAINT FK_TELEFONE
FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIO;

INSERT INTO FUNCIONARIO VALUES(1,'MAURÍCIO');
INSERT INTO TELEFONE VALUES(10,'11978578992',1);


/* A CONSTRAINT DE INTEGRIDADE REFERENCIAL (fk) CHECA A INTEGRIDADE LOGO
APÓS O COMANDO DE DML INSERT / DELETE / UPDATE - NÃO POSSIBILITANDO ASSIM
A INSERÇÃO DE REGISTROS SEM REFERÊNCIA */

/* VERIFICANDO O ESTADO DAS CONSTAINTS */

SELECT CONSTRAINT_NAME, DEFERRABLE, DEFERRED
FROM USER_CONSTRAINTS WHERE TABLE_NAME IN('FUNCIONARIO','TELEFONE');


/* APAGANDO A CONSTRAINT PARA MEXER NO COMPORTAMENTO DELA */


ALTER TABLE TELEFONE DROP CONSTRAINT FK_TELEFONE;

/* RECRIANDO A CONSTRAINT */


ALTER TABLE TELEFONE ADD CONSTRAINT FK_TELEFONE
FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIO
DEFERRABLE;


SELECT CONSTRAINT_NAME, DEFERRABLE AS ATRASADA, DEFERRED AS VERIFICACAO
FROM USER_CONSTRAINTS WHERE TABLE_NAME IN('FUNCIONARIO','TELEFONE');

/* MUDANDO PARA A DTL */

SET CONSTRAINTS ALL DEFERRED;

COMMIT;










