
-- CRIANDO UMA TABLESPACE DE MARKETING

SELECT * FROM FUNCIONARIOS;

SELECT * FROM CAMPANHAS;

CREATE TABLESPACE MARKETING
DATAFILE 'C:/DATA/MKT_01.DBF'
SIZE 10M AUTOEXTEND
ON NEXT 10M
MAXSIZE 100M;


CREATE TABLE CAMPANHAS(
    IDCAMPANHA INT PRIMARY KEY,
    NOME VARCHAR(30)
)TABLESPACE MARKETING;

INSERT INTO CAMPANHAS VALUES(SEQ_GERAL.NEXTVAL,'PRIMAVERA');
INSERT INTO CAMPANHAS VALUES(SEQ_GERAL.NEXTVAL,'VERAO');
INSERT INTO CAMPANHAS VALUES(SEQ_GERAL.NEXTVAL,'INVERNO');

-- COLOCANDO A TABLESPACE OFF LINE

ALTER TABLESPACE RECURSOS_HUMANOS OFFLINE;


-- APONTAR PARA O DICIONARIO DE DADOS

ALTER TABLESPACE RECURSOS_HUMANOS
RENAME DATAFILE 'C:/DATA/RH_01.DBF' TO 'C:/PRODUCAO/RH_01.DBF';

DROP TABLE ALUNO;

CREATE TABLE ALUNO(
    IDALUNO     INT PRIMARY KEY,
    NOME        VARCHAR2(30),
    EMAIL       VARCHAR2(30),
    SALARIO     NUMBER(10, 2)
);


CREATE SEQUENCE SEQ_EXEMPLO;

INSERT INTO ALUNO VALUES(SEQ_EXEMPLO.NEXTVAL, 'JOAO', 'JOAO@GMAIL.COM',1000.00);
INSERT INTO ALUNO VALUES(SEQ_EXEMPLO.NEXTVAL, 'CLARA', 'CLARA@GMAIL.COM',2000.00);
INSERT INTO ALUNO VALUES(SEQ_EXEMPLO.NEXTVAL, 'CELINA', 'CELINA@GMAIL.COM',3000.00);


SELECT * FROM ALUNO;


CREATE TABLE ALUNO2(
    IDALUNO     INT PRIMARY KEY,
    NOME        VARCHAR2(30),
    EMAIL       VARCHAR2(30),
    SALARIO     NUMBER(10, 2)
);


INSERT INTO ALUNO2 VALUES(SEQ_EXEMPLO.NEXTVAL, 'JOAO', 'JOAO@GMAIL.COM',1000.00);
INSERT INTO ALUNO2 VALUES(SEQ_EXEMPLO.NEXTVAL, 'CLARA', 'CLARA@GMAIL.COM',2000.00);
INSERT INTO ALUNO2 VALUES(SEQ_EXEMPLO.NEXTVAL, 'CELINA', 'CELINA@GMAIL.COM',3000.00);


SELECT * FROM ALUNO2;


/* ROWID E ROWNUM */

SELECT ROWID, IDALUNO, NOME, EMAIL FROM ALUNO;

SELECT ROWID,ROWNUM, IDALUNO, NOME, EMAIL FROM ALUNO2;

SELECT NOME, EMAIL FROM ALUNO WHERE ROWNUM <= 2;


/* PROCEDURE */

CREATE OR REPLACE PROCEDURE BONUS(P_IDALUNO IN ALUNO.IDALUNO%TYPE, P_PERCENT NUMBER
)
AS
BEGIN
    UPDATE ALUNO
    SET SALARIO = SALARIO + (SALARIO * (P_PERCENT / 100))
    WHERE P_IDALUNO = P_IDALUNO;
    
    
    END;
    /

SELECT * FROM ALUNO;


CALL BONUS(3,10);



/* AS TRIGGERS DEVEM TER O TAMANHO MAXIMO DE 32K
NAO EXECUTAM COMANDOS DE DIL - COMMIT, ROLLBACK E SAVEPOINTS */


/* VALIDACAO */

CREATE OR REPLACE TRIGGER CHECK_SALARIO
BEFORE INSERT OR UPDATE ON ALUNO
FOR EACH ROW
BEGIN
        IF :NEW.SALARIO < 2000 THEN
            RAISE_APLICATION_ERROR(-20000, 'VALOR INCORRETO');
        END IF;       
END;
/

SHOW ERRORS;


INSERT INTO ALUNO VALUES(SEQ_EXEMPLO.NEXTVAL, 'MAFRA', 'MAFRA@GMAIL.COM',100.00);




























