
CREATE TABLESPACE MARKETING
DATAFILE 'C:/DATA/MKT_01.DBF'
SIZE 10M AUTOEXTEND
ON NEXT 10M
MAXSIZE 100M;


CREATE TABLE CAMPANHAS(
    IDCAMPANHA INT PRIMARY KEY,
    NOME VARCHAR(30)
)TABLESPACE MARKETING;

INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL,'PRIMAVERA');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL,'VERAO');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL,'INVERNO');


SELECT * FROM FUNCIONARIOS;

SELECT * FROM CAMPANHAS;




ALTER TABLESPACE RECURSOS_HUMANOS OFFLINE;


ALTER TABLESPACE RECURSOS_HUMANOS
RENAME DATAFILE 'C:/DATA/RH_01.DBF' TO 'C:/PRODUCAO/RH_01.DBF';

-- TORNANDO A TABLESPACE ON-LINE

ALTER TABLESPACE RECURSOS_HUMANOS ONLINE;






