SHOW ERRORS;

SELECT TRIGGER_NAME, TRIGGER_BODY
FROM USER_TRIGGERS;


CREATE OR REPLACE TRIGGER CHECK_SALARIO
BEFORE INSERT OR UPDATE ON FUNCIONARIOS
FOR EACH ROW
BEGIN
    IF :NEW.SALARIO < 2000 THEN
        RAISE_APPLICATION_ERROR(-20000, 'VALOR INCORRETO: O salário não pode ser menor que R$ 2000.');
    END IF;
END;
/

DROP TRIGGER CHECK_SALARIO;

DESC FUNCIONARIOS;


-- TRIGGER DE EVENTO

CREATE TABLE AUDITORIA(
    DATA_LOGIN DATE,
    LOGIN VARCHAR2(30)
);


CREATE OR REPLACE PROCEDURE LOGPROC IS
BEGIN
    INSERT INTO AUDITORIA(DATA_LOGIN,LOGIN)
    VALUES(SYSDATE,USER);
END LOGPROC;
/

SELECT USER FROM DUAL;


-- FALHA DE LOGON

CREATE OR REPLACE TRIGGER FALHA_LOGON
AFTER SERVERERROR
ON DATABASE
BEGIN
        IF (IS_SERVERERROR(1017)) THEN
            INSERT INTO AUDITORIA(DATA_LOGIN,LOGIN)
            VALUES(SYSDATE,'ORA-1017');
        END IF;
END FALHA_LOGON;
/


-- 1004: DEFAULT USERNAME FEATUE NOT SUPPORED
-- 1005: PASSWORD NULO
-- 1045: PRIVILÉGIO INSUFICIENTE

-- TRIGGER

CREATE TABLE USUARIO(
    ID INT,
    NOME VARCHAR2(30)
);

CREATE TABLE BKP_USER(
    ID INT,
    NOME VARCHAR2(30)
);


INSERT INTO USUARIO VALUES(1, 'JOAO');
INSERT INTO USUARIO VALUES(2, 'CLARA');

COMMIT;

SELECT * FROM USUARIO;

CREATE OR REPLACE TRIGGER LOG_USUARIO
BEFORE DELETE ON USUARIO
FOR EACH ROW
BEGIN
    INSERT INTO BKP_USER VALUES
    (:OLD.ID, :OLD.NOME);
END;
/

DELETE FROM USUARIO WHERE ID = 1;

SELECT * FROM BKP_USER;
